# -------------- setting ---------------
exp_dir: exp/
mode: train # train, test
gpu_ids: [0] # 

# -------------- model ---------------
model: 
  name: UNet
  in_nc: 3
  out_nc: 3

pretrained_weight: ~


# -------------- data ---------------
train_dataloader:
  dataset:
    name: DeblurDataset
    image_dir: dataset/GOPRO_demo/train
    transform: {random_crop: 256, random_hflip: true, random_vflip: true}
  batch_size: 4
  num_workers: 8
  shuffle: true
  pin_memory: true

test_dataloader:
  dataset:
    name: DeblurDataset
    image_dir: dataset/GOPRO_demo/test
    transform: ~
  batch_size: 1
  num_workers: 4
  shuffle: false
  pin_memory: true


# -------------- optimization ---------------
optimizer:
  name: Adam
  lr: 1e-4
  weight_decay: 0.0
lr_scheduler:
  name: MultiStepLR
  milestones: [100, 600, 1100]
  gamma: 0.5
  warmup:
    epoch: -1
    strategy: linear # linear, cos, constant
    init_lr: 0.0
loss:
  name: WeightedLoss
  CharbonnierLoss: 0.5
  EdgeLoss: 0.5

# -------------- train ---------------
num_epoch: 10
resume_state: ~
fabric_conf:
  accelerator: "cuda" # "cpu", "cuda", "mps", "gpu", "tpu", "auto"
  precision: "bf16-mixed" # "32", "64", "bf16-mixed", "16-mixed"
  strategy:  "ddp" # "dp", "ddp", "ddp_spawn", "deepspeed", "fsdp", "auto"

logger_freq: 1
save_freq: 5
valid_freq: 1
save_val_image: true

# -------------- test ---------------
save_test_image: true
torch_compile: ~
  # mode: default # default, reduce-overhead, max-autotune
test_on_cpu: false